### ISSUE TITLE
TODO for version 1.0

### ISSUE THREAD

**Issue by andymac-2** [andymac-2/raytrace#1]
- [ ] Cylinders, and other basic geometry
- [ ] Meshes
- [ ] Textures
- [ ] Fractals
- [ ] Input file format and parser
- [ ] Diffuse light
- [ ] Bidirectional ray tracing
- [ ] Camera object
